# Generated by Django 3.2.7 on 2021-11-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/default_image.png', null=True, upload_to='userprofile'),
        ),
    ]
