# Generated by Django 3.2.7 on 2021-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offername',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
