# Generated by Django 3.2.7 on 2021-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_offers_offername'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_offer_avail',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offername',
            field=models.CharField(max_length=200),
        ),
    ]
