# Generated by Django 3.2.7 on 2021-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20211013_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='offer',
            new_name='dis_percentage',
        ),
        migrations.AddField(
            model_name='offers',
            name='is_avail',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
