# Generated by Django 3.2.7 on 2021-10-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20211014_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='is_avail',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
