# Generated by Django 3.2.7 on 2021-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_offers_is_avail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='product',
            name='expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
