# Generated by Django 3.2.7 on 2021-10-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20211014_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='startdate',
        ),
    ]
