# Generated by Django 3.2.7 on 2021-10-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_auto_20211028_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category_offers',
            new_name='CategoryOffers',
        ),
    ]
