# Generated by Django 3.2.7 on 2021-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_rename_category_offers_categoryoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_offer_avail',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_offer_price',
            field=models.FloatField(null=True),
        ),
    ]
