# Generated by Django 3.2.7 on 2021-11-02 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0013_auto_20211028_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='couponOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_title', models.CharField(max_length=30, unique=True)),
                ('coupon_limit', models.IntegerField()),
                ('coupon_offer', models.FloatField()),
                ('coupon_end', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
