# Generated by Django 3.2.7 on 2021-11-03 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderproduct_options'),
        ('admin_panel', '0014_couponoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponoffer',
            name='order_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderproduct'),
        ),
    ]
