# Generated by Django 3.2.7 on 2021-11-04 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_auto_20211103_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponused',
            name='order_details',
        ),
    ]
