# Generated by Django 3.2.7 on 2021-11-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_couponused_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponused',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
