# Generated by Django 3.2.7 on 2021-11-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_couponused_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_offer_avail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_offer_avail',
            field=models.BooleanField(default=False),
        ),
    ]
