# Generated by Django 3.2.7 on 2021-11-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_bannerupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
