# Generated by Django 3.2.7 on 2021-11-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20211111_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
    ]
