# Generated by Django 3.2.7 on 2021-11-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
