# Generated by Django 3.2.7 on 2021-11-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
